offspot/imager-service

- manager/requirements.txt
See https://github.com/kiwix/cardshop/network/alert/manager/requirements.txt/django/open
> Fix Django security issue

- manager/manager/templates/configuration_list.html
> Change new configuration button label to 'New configuration'

- scheduler/src/templates/recipient_order_failed.html
> Remove sentence about refunding in email template

- scheduler/src/emailing.py
- scheduler/src/requirements.txt
- scheduler/src/templates/macros.html
- scheduler/src/templates/recipient_image_uploaded_public.html
- scheduler/src/utils/mongo.py
- scheduler/src/utils/templates.py
- workers/requirements.txt
- workers/worker/tasks/create.py
Creator worker and scheduler support for creating, uploading and linking to torrent files
> Torrent support

- manager/manager/scheduler.py
- manager/manager/templates/scheduler.html
- manager/manager/templatetags/manager.py
- manager/manager/urls.py
- manager/manager/views/admin.py
- manager/manager/views/scheduler.py
- scheduler/src/entrypoint.sh
- scheduler/src/main.py
- scheduler/src/periodic-tasks.py
- scheduler/src/routes/autoimages.py
- scheduler/src/routes/orders.py
- scheduler/src/utils/mongo.py
Added AutoImages to scheduler
- mongo model
- periodic task to
- create Order once expired
- update AutoImage on build/completion
- new /auto-images/ endpoint
- list AutoImages
- create/delete AutoImages
- get url as JSON
- redirect to url
Added AutoImages to manager
- List AutoImages in scheduler page with status
- create new AutoImage from config
- delete AutoImage
- links to:
- last url
- permanent url for JSON (to get actual url)
- permanent url for redirect (to actual url)
Fixes #112
Invalidates #118
> Auto images

- manager/Dockerfile
- manager/entrypoint.sh
- manager/nginx.conf
- manager/status/main.py
- manager/status/requirements.txt
- manager/status/templates/status.html
- manager/uwsgi-manager.ini
- manager/uwsgi-status.ini
- independent service requiring the nginx proxy but not tied to manager code
- single web page listing systems and status
- using uwsgi emperor mode to support both manager and status in same container
Also updated base image to python3.8 and fixed periodic tasks cron for manager
Fixes #114
> Added Health Check service

- manager/status/main.py
- http requests now bound by a timeout (5s)
- checks done asynchronously
> Improved health-check speed

- manager/manager/scheduler.py
- manager/manager/templates/scheduler.html
- manager/manager/views/scheduler.py
- scheduler/src/emailing.py
- scheduler/src/periodic-tasks.py
- scheduler/src/routes/__init__.py
- scheduler/src/routes/autoimages.py
- scheduler/src/routes/channels.py
- scheduler/src/routes/home.py
- scheduler/src/routes/orders.py
- scheduler/src/routes/tasks.py
- scheduler/src/routes/users.py
- scheduler/src/routes/warehouses.py
- scheduler/src/routes/workers.py
- scheduler/src/templates/macros.html
- scheduler/src/templates/recipient_image_uploaded_public.html
- scheduler/src/utils/mongo.py
- scheduler/src/utils/templates.py
> Auto images improvements

- scheduler/src/routes/orders.py
- scheduler/src/utils/mongo.py
- scheduler/src/utils/templates.py
- image names now set in Order at order creation ({id}.img)
- auto-images now named after slug, period and random string
> Image now named in order

- manager/Dockerfile
- manager/manager/settings.py
- manager/manager/urls.py
- manager/manager/views/api.py
- manager/manager/views/scheduler.py
- scheduler/src/templates/recipient_image_uploaded_public.html
> Create manager account

- manager/manager/templates/home.html
Check that `<a href="{% url 'order_list' %}">` does in fact redirect to Orders.
> Minor update to simplify onboarding

- scheduler/src/routes/workers.py
estimate durations of tasks in the pipe
> new /workers/load endpoint

- manager/manager/models.py
- manager/manager/templates/_label_for.html
Also resolves #78 by setting default hotspot name to `Kiwix`
> Minor wording update.

- scheduler/src/templates/recipient_order_failed.html
Removed most non-actionable information.
> Simplified text

- scheduler/src/routes/stripe.py
- scheduler/src/templates/stripe/shop.html
Deprecate yearly option, change Wikipedia-only pricing, minor wording corrections + typo
> Update to shop

- manager/manager/pibox/content.py
- manager/manager/pibox/data.py
- manager/manager/pibox/util.py
- manager/requirements.txt
- whost/requirements.txt
- whost/whost/network.py
- workers/worker/base.py
Sizes calculations changed a bit in hotspot, so we needed to reflect those changes here.
Also updated to pyYAML5 for security and now using libyaml for faster parsing.
Added task cancelation support in worker.
> Using same calculations as hotspot 

- manager/manager/templates/base.html
Update base.html template to include navigation links for authenticated users only. fixes #81
> Hide Menu if not logged-in

- scheduler/src/templates/stripe/email_success_image.html
clarified that the Pi zero 2W is not suitable
> Email success image: Zero 2W not supported

- scheduler/src/templates/stripe/shop.html
Required card size changed from 256 to 512GB
> Update shop.html to increase size of preppers package

- scheduler/src/templates/stripe/shop.html
Added link to online demos
Dialed back prepper image to 256GB
> updated custom image descriptions

- scheduler/src/templates/stripe/success_image.html
> Updated success_image.html

- scheduler/src/templates/stripe/shop.html
Improved content description to better reflect what is in it.
> cleared content description

- scheduler/src/templates/stripe/shop.html
Removed Customize your network’s name and dashboard looks
> Updated product description for complete imager service

- scheduler/src/templates/stripe/shop.html
https://github.com/offspot/shop/issues/89
> Shop to offer both HW and OS options together
